image: Visual Studio 2015

install:
  - nuget-restore.cmd

configuration:
  - Release

build:
  project: Its.Cqrs.sln
  publish_nuget: true

test_script:
- ps: nunit3-console (ls . -filter '*.Tests.dll' -r | ?{$_.FullName.Contains('bin\Release\')}  | sort-object -Unique -Property Name | % FullName) --agents=1 --result=myresults.xml`;format=AppVeyor
